name = "magnus-api"
main = "src/index.ts"
compatibility_date = "2025-12-31"

[ai]
binding = "AI"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "magnus-bucket"

[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "magnus-index-768"

[[d1_databases]]
binding = "DB"
database_name = "lumenary_db"
# TODO: replace with the real D1 database ID.
database_id = "e7a8185c-f8df-457b-a37c-911209ef992b"
